apiVersion: v1
kind: Secret
metadata:
  name: ogm-{{ .Release.Name }}-secrets
  labels:
    app: {{ .Values.auctionservice.labels.app }}
    secretEnv: {{ .Values.env }}
    targetApp: {{ .Values.targetApp }}
    namespace: {{ .Values.namespace }}
    owner: {{ .Values.owner }}
stringData:

