apiVersion: apps/v1
kind: Deployment
metadata:
  name: ogm-{{ .Release.Name }}-deploy
  labels:
    app: {{ .Values.competitionservice.labels.app }}
    env: {{ .Values.env }}
    targetApp: {{ .Values.targetApp }}
    namespace: {{ .Values.namespace }}
    owner: {{ .Values.owner }}
spec:
  selector:
    matchLabels:
      app: ogm-{{ .Release.Name }}-container
  template:
    metadata:
      labels:
        app: ogm-{{ .Release.Name }}-container
        env: {{ .Values.env }}
        targetApp: {{ .Values.targetApp }}
        namespace: {{ .Values.namespace }}
        owner: {{ .Values.owner }}
    spec:
      initContainers:
        - name: db-migrator-container
          image: {{ .Values.competitionservice.deployment.init.image }}
          imagePullPolicy: {{ .Values.competitionservice.deployment.imagePullPolicy }}
          args:
            - "dotnet"
            - "./competitionservice.DatabaseMigrator.dll"
            - "--connection-string-source=env"
            - "--connection-string-env-variable-name=DbConn"
          env:
            - name: DbConn
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sharedSecrets }}
                  key: auctionDb
      containers:
        - name: ogm-{{ .Release.Name }}-container
          image: {{ .Values.competitionservice.deployment.image }}
          imagePullPolicy: {{ .Values.competitionservice.deployment.imagePullPolicy }}
          resources:
            requests:
              memory: {{ .Values.competitionservice.deployment.resources.requests.memory }}
              cpu: {{ .Values.competitionservice.deployment.resources.requests.cpu }}
            limits:
              memory: {{ .Values.competitionservice.deployment.resources.limits.memory }}
              cpu: {{ .Values.competitionservice.deployment.resources.limits.cpu }}                
          env:
            - name: "competitionservice_ConnectionStrings__AuctionDb"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sharedSecrets }}
                  key: auctionDb
            - name: "ASPNETCORE_ENVIRONMENT"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sharedSecrets }}
                  key: aspNetEnv
            - name: "competitionservice_HttpPort"
              value: "{{ .Values.competitionservice.containerPort.http }}"
            - name: "competitionservice_GrpcPort"
              value: "{{ .Values.competitionservice.containerPort.grpc }}"
          ports:
            - containerPort: {{ .Values.competitionservice.containerPort.http }}
              name: http-port
            - containerPort: {{ .Values.competitionservice.containerPort.grpc }}
              name: grpc-port
          startupProbe:
            httpGet:
              path: /healthz/live
              port: http-port
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: http-port
            initialDelaySeconds: {{ .Values.competitionservice.deployment.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.competitionservice.deployment.probe.periodSeconds }}
            timeoutSeconds: {{ .Values.competitionservice.deployment.probe.timeoutSeconds }}    
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: http-port
            initialDelaySeconds: {{ .Values.competitionservice.deployment.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.competitionservice.deployment.probe.periodSeconds }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
