---

version: "3.8"

services:
  competition_test_postgres:
    container_name: CompetitionService_TestPostgres
    image: postgres:13.3
    pull_policy: if_not_present
    environment:
      - POSTGRES_DB=CompetitionDbIntegrationTest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d CompetitionDbIntegrationTest"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    logging:
      driver: none

  competition_test_migrator:
    container_name: CompetitionService_TestMigrator
    image: mcr.microsoft.com/dotnet/sdk:6.0
    pull_policy: if_not_present
    environment:
      - ASPNETCORE_ENVIRONMENT=IntegrationTest
      - DbConn=Host=competition_test_postgres;Port=5432;Database=CompetitionDbIntegrationTest;User Id=postgres;Password=postgres
    volumes:
      - ./../../src:/app-migrator/src
      - ./../../devops:/app-migrator/devops
    command:
      [
        "dotnet",
        "run",
        "--project",
        "/app-migrator/src/CompetitionService.DatabaseMigrator/CompetitionService.DatabaseMigrator.csproj",
        "--connection-string-source",
        "env",
        "--connection-string-env-variable-name",
        "DbConn"
      ]
    depends_on:
      competition_test_postgres:
        condition: service_healthy

  integration_tests:
    container_name: CompetitionService_IntegrationTests
    build:
      context: ./../../
      dockerfile: ./tests/CompetitionService.IntegrationTests/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=IntegrationTest
      - CompetitionService_ConnectionStrings__CompetitionDb=Host=competition_test_postgres;Port=5432;Database=CompetitionDbIntegrationTest;User Id=postgres;Password=postgres
    depends_on:
      competition_test_migrator:
        condition: service_completed_successfully

  functional_tests:
    container_name: CompetitionService_FunctionalTests
    build:
      context: ./../../
      dockerfile: ./tests/CompetitionService.FunctionalTests/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=IntegrationTest
      - CompetitionService_ConnectionStrings__CompetitionDb=Host=competition_test_postgres;Port=5432;Database=CompetitionDbIntegrationTest;User Id=postgres;Password=postgres
    depends_on:
      competition_test_migrator:
        condition: service_completed_successfully

volumes:
  postgres_volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
