env: dev
targetApp: auctionservice
namespace: dev
owner: NikitaPrachkovski

imagePullSecrets: ogame-container-registry
sharedSecrets: ogame-dotnet-secrets

auctioncreator:
  labels:
    app: auctioncreator
  
  deployment:
    image: docker-hub.effective-soft.com:5000/auctionservice-event-creator:1.0.3
    imagePullPolicy: Always

auctionconsumers:
  labels:
    app: auctionconsumers

  containerPort:
    http: 80

  deployment:
    image: docker-hub.effective-soft.com:5000/auctionservice-consumers:1.1.9
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    imagePullPolicy: Always

    probe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 1

auctionservice:
  containerPort:
    http: 80
    grpc: 8080
  servicePort: 
    http: 8091
    grpc: 8191

  labels:
    app: auctionservice

  deployment:
    image: docker-hub.effective-soft.com:5000/auctionservice-grpc-api:1.0.1
    init:
      image: docker-hub.effective-soft.com:5000/auctionservice-database-migrator:1.0.0
    imagePullPolicy: Always
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    probe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 1

  autoscaling:
    replicas:
      min: 1
      max: 2
    cpuAverageUtilization: 70
    memoryAverageUtilization: 80

  service:
    type: ClusterIP
